config_version = 2

[bar.default]
start = [ "launcher", "cpu", "ram", "temp" ]
center = [ "workspaces" ]
end = [ "indicator", "network", "bluetooth", "volume", "brightness", "battery", "clock", "notifications" ]
margin_ends = 0
position = "left"
radius_bottom_left = 0
radius_top_left = 0
scale = 1.2
thickness = 50
widget_spacing = 14
shadow = false

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660.0

[location]
address = "Sapporo"

[lockscreen]
blur_intensity = 0.0

[lockscreen_widgets]
enabled = false
schema_version = 2

[shell]
niri_overview_type_to_launch_enabled = true

    [shell.launcher]
    show_icons = false

    [shell.panel]
    borders = false
    shadow = false
    transparency_mode = "solid"
    open_near_click_control_center = true

[theme]
    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "ghostty", "niri" ]
    community_ids = [ "yazi" ]

[wallpaper]
directory = "/home/takumi/Pictures/Wallpapers"

[backdrop]
enabled = false
blur_intensity = 0.0
tint_intensity = 0.5

[plugins]
enabled = [ "takumi/fcitx5-indicator" ]

    [[plugins.source]]
    kind = "path"
    location = "/home/takumi/.config/noctalia/plugins"
    name = "local"

[widget.battery]
display_mode = "graphic"
scale = 0.8
show_label = false

[widget.clipboard]
enabled = false

[widget.launcher]
color = "tertiary"
glyph = "activity-heartbeat"

[widget.network]
show_label = false

[widget.volume]
show_label = false

[widget.workspaces]
display = "none"

[widget.brightness]
show_label = false

[widget.ram]
show_label = false

[widget.cpu]
show_label = false

[widget.temp]
show_label = false

[widget.indicator]
type = "takumi/fcitx5-indicator:indicator"
