config_version = 2

[bar.default]
start = [ "launcher", "cpu", "ram", "temp" ]
center = [ "workspaces" ]
end = [ "indicator", "network", "bluetooth", "volume", "brightness", "battery", "clock", "notifications" ]
margin_ends = 0
position = "left"
radius_bottom_left = 0
radius_top_left = 0
scale = 1.2
thickness = 50
widget_spacing = 14
shadow = false

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660.0

[location]
address = "Sapporo"

[lockscreen]
blur_intensity = 0.0
transition = []

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@eDP-1",
    "lockscreen-login-box@DP-2",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-2"]
    box_height = 70.0
    box_width = 384.0
    cx = 1280.0
    cy = 784.0
    output = "DP-2"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-2".settings]
        background_color = "surface_variant"
        background_opacity = 1.0
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "compact"
        show_caps_lock = true
        show_keyboard_layout = false
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = false
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 384.0
    cx = 960.0
    cy = 664.0
    output = "eDP-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 1.0
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "compact"
        show_caps_lock = true
        show_keyboard_layout = false
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = false
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 192.0
    box_width = 512.0
    cx = 1280.0
    cy = 653.0
    output = "DP-2"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background_opacity = 0.0
        center_text = true
        clock_style = "digital"
        color = "secondary"
        font_family = "Audiowide"
        format = "{:%H:%M}"
        shadow = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 192.0
    box_width = 512.0
    cx = 960.0
    cy = 533.0
    output = "eDP-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        background_opacity = 0.0
        center_text = true
        clock_style = "digital"
        color = "secondary"
        font_family = "Audiowide"
        format = "{:%H:%M}"
        shadow = false

[shell]
font_family = "Inter Tight"
niri_overview_type_to_launch_enabled = true

    [shell.launcher]
    show_icons = false

    [shell.panel]
    borders = false
    shadow = false
    transparency_mode = "solid"
    open_near_click_control_center = true

[theme]
    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "ghostty", "niri" ]
    community_ids = [ "yazi" ]

[wallpaper]
directory = "/home/takumi/Pictures/Wallpapers"

[backdrop]
enabled = true
blur_intensity = 1.0
tint_intensity = 0.5

[plugins]
enabled = [ "takumi/fcitx5-indicator" ]

    [[plugins.source]]
    kind = "path"
    location = "/home/takumi/.config/noctalia/plugins"
    name = "local"

[widget.battery]
display_mode = "graphic"
scale = 0.8
show_label = false

[widget.clipboard]
enabled = false

[widget.launcher]
color = "tertiary"
glyph = "activity-heartbeat"

[widget.network]
show_label = false

[widget.volume]
show_label = false

[widget.workspaces]
show_labels = false
pill_scale = 0.80
active_pill_size = 1.0
empty_color = "outline"
focused_color = "secondary"
occupied_color = "primary"
urgent_color = "primary"

[widget.brightness]
show_label = false

[widget.ram]
show_value = false

[widget.cpu]
show_value = false

[widget.temp]
show_value = false

[widget.indicator]
type = "takumi/fcitx5-indicator:indicator"

[notification]
border = false
position = "top_right"

[osd]
border = false
position = "bottom_center"
