env:
  TERM: xterm-256color

colors:
  primary:
    background: '#000000'
    foreground: '#ffffff'

font:
  size: 10
  normal:
    family: 'JetBrainsMono'
    style: Regular
  bold:
    family: 'JetBrainsMono'
    style: Bold
  italic:
    family: 'JetBrainsMono'
    style: Italic
  bold_italic:
    family: 'JetBrainsMono'
    style: Bold Italic

window:
  decorations: none
  startup_mode: Maximized
  title: Terminal
  dynamic_title: false
  padding:
    x: 30
    y: 30
  opacity: 0.90
