#!/bin/sh

DOTPATH=~/dots

for f in .??*
do
    case $f in
        ".git"|".gitignore")
            ;;
        *)
            ln -snfv "$DOTPATH"/"$f" ~/"$f"
            ;;
    esac
done

cp -rT ./config/ ~/.config/
ln -snfv "$DOTPATH"/.vimrc ~/.config/nvim/init.vim
