#!/bin/sh

cd "$(dirname "$0")" || exit

for f in .??*
do
    case "$f" in
        .git*)
            ;;
        *)
            ln -snfv "$PWD"/"$f" ~/"$f"
            ;;
    esac
done

find config -type f | while read -r f
do
    mkdir -p ~/."$(printf "%s" "$f" | rev | cut -d '/' -f 2- | rev)"
    ln -snfv "$PWD"/"$f" ~/."$f"
done
