#!/bin/sh

alias l='ls'
alias la='ls -a'
alias ll='ls -l'
alias lh='ls -lh'
alias lla='ls -la'
alias less='less -R'
alias grep='grep --color=auto'
alias fgrep='grep -E --color=auto'
alias egrep='grep -F --color=auto'
alias e='if ! ps ax | grep emacs | grep -q " --daemon"; then emacs --daemon; fi; emacs -nw'
alias diff='diff -uprN'
alias ag='ag --color-match "39;46" --color-path "1;34" --color-line-number "1;30"'
alias essh='ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=error'
alias escp='scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=error'
alias minicom='minicom -c on'
alias icat='chafa -f kitty'
alias zstc='tar --zstd -cvf'
alias zstx='tar --zstd -xvf'
alias nix-shell='nix-shell --run "$SHELL"'

case "$(uname)" in
    Darwin)
        alias ls='ls -FG'
        ;;
    Linux)
        alias ls='ls --color -F'
        alias open='xdg-open'
        ;;
esac

if command -v nvim > /dev/null 2>&1; then
    alias vi=nvim
elif command -v vim > /dev/null 2>&1; then
    alias vi=vim
fi

if command -v podman > /dev/null 2>&1; then
    alias docker=podman
fi

if command -v bat > /dev/null 2>&1; then
    alias cat='bat --paging=never --style=plain'
    alias less='bat --paging=always'
fi

if command -v loupe > /dev/null 2>&1; then
    alias eog='loupe'
fi
