[Metadata]
Name=Minimal
Version=1
Author=takumi
Description=Minimal pure-black theme without borders
ScaleWithDPI=True

[InputPanel]
NormalColor=#f6f5f4
HighlightCandidateColor=#ffffff
HighlightColor=#ffffff
HighlightBackgroundColor=#484848
CandidateLabelColor=#9a9996
HighlightCandidateLabelColor=#deddda
CandidateCommentColor=#9a9996
HighlightCandidateCommentColor=#deddda
PageButtonAlignment=Last Candidate

[InputPanel/ContentMargin]
Left=6
Top=6
Right=6
Bottom=6

[InputPanel/Background]
Image=background.png

[InputPanel/Background/Margin]
Left=20
Top=20
Right=20
Bottom=20

[InputPanel/Highlight]
Image=highlight.png

[InputPanel/Highlight/Margin]
Left=14
Top=5
Right=14
Bottom=5

[InputPanel/TextMargin]
Left=14
Top=5
Right=14
Bottom=5

[InputPanel/PrevPage]
Image=prev.png

[InputPanel/PrevPage/ClickMargin]
Left=5
Top=5
Right=5
Bottom=5

[InputPanel/NextPage]
Image=next.png

[InputPanel/NextPage/ClickMargin]
Left=5
Top=5
Right=5
Bottom=5

[Menu]
NormalColor=#f6f5f4
HighlightCandidateColor=#ffffff
Spacing=2

[Menu/ContentMargin]
Left=6
Top=6
Right=6
Bottom=6

[Menu/Background]
Image=background.png

[Menu/Background/Margin]
Left=20
Top=20
Right=20
Bottom=20

[Menu/Highlight]
Image=highlight.png

[Menu/Highlight/Margin]
Left=14
Top=5
Right=14
Bottom=5

[Menu/TextMargin]
Left=14
Top=5
Right=14
Bottom=5

[Menu/SubMenu]
Image=next.png

[Menu/Separator]
Color=#3d3d3d
