#!/bin/sh

clock () {
        DATETIME=$(date "+%Y-%m-%d %T")
        echo -n "$DATETIME"
}

battery () {
    BAT=/sys/class/power_supply/BAT0

    if [ ! -e $BAT ]; then
        exit
    fi

    CAPACITY=$(cat $BAT/capacity)
    STATUS=$(cat $BAT/status)

    if [ "$STATUS" != "Discharging" ]; then
        CAPACITY="+${CAPACITY}"
    fi

    echo -n "${CAPACITY}%"
}

im () {
    case $(fcitx5-remote) in
        1 )
            echo -n "en"
            ;;
        2 )
            echo -n "jp"
            ;;
    esac
}

echo $(im) $(battery) $(clock)
