#!/bin/sh

CMD_ON="pactl set-sink-mute @DEFAULT_SINK@ off"
CMD_TOGGLE="pactl set-sink-mute @DEFAULT_SINK@ toggle"
CMD_UP="pactl set-sink-volume @DEFAULT_SINK@ +5%"
CMD_DOWN="pactl set-sink-volume @DEFAULT_SINK@ -5%"
CMD_MIC="pactl set-source-mute @DEFAULT_SOURCE@ toggle"
CMD_GET_VOLUME="pactl get-sink-volume @DEFAULT_SINK@"
CMD_PLAY_ICON="mpv /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga"

case "$1" in
    "up" )
        $CMD_ON
        $CMD_UP
        $CMD_PLAY_ICON &
        ;;
    "down" )
        $CMD_ON
        $CMD_DOWN
        $CMD_PLAY_ICON &
        ;;
    "mute" )
        $CMD_TOGGLE
        $CMD_PLAY_ICON &
        ;;
    "mic" )
        $CMD_MIC
        ;;
esac > /dev/null 2>&1

$CMD_GET_VOLUME | head -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,'
