format = """
$container\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$line_break\
$python\
$nix_shell\
$character\
"""

[hostname]
format = "[$hostname]($style) "
style = "red bold"
ssh_only = true

[directory]
format = "[$path]($style) "
style = "cyan bold"
truncation_length = 3
truncation_symbol = ".../"
truncate_to_repo = false

[git_branch]
format = "[$branch]($style)"
style = "blue bold"

[git_state]
format = "[⚠]($style)"
style = "yellow bold"

[git_status]
format = "[$all_status]($style) "
style = "red bold"

[nix_shell]
format = "[$symbol]($style)"
style = "#405d99 bold"
symbol = "*"

[character]
success_symbol = "[➔](green bold)"
error_symbol = "[➔](red bold)"

[container]
format = '[$name]($style) '
style = "#e95420 bold"

[python]
format = '[+]($style)'
style = 'yellow bold'
