format = """
$container\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$line_break\
$shell\
$python\
$nix_shell\
$character\
"""

[character]
success_symbol = "[➔](#ff6600 bold)"
error_symbol = "[➔](#555555 bold)"

[container]
format = '[$name]($style) '
style = "#e95420 bold"

[directory]
format = "[$path]($style) "
style = "#9daae2 bold"
truncation_length = 3
truncation_symbol = ".../"
truncate_to_repo = false

[git_branch]
format = "[$branch]($style)"
style = "#555555 bold"

[git_state]
format = "[⚠]($style)"
style = "#eed202 bold"

[git_status]
format = "[$all_status]($style) "
style = "#cc0000 bold"
untracked = '.'

[hostname]
format = "[$hostname]($style) "
style = "#cc0000 bold"
ssh_only = true

[nix_shell]
format = "[$symbol]($style)"
style = "#405d99 bold"
symbol = "*"

[python]
format = '[+]($style)'
style = '#ffd43b bold'
detect_extensions = []
detect_files = []

[shell]
format = '[$indicator]($style)'
style = '#4eaa25 bold'
bash_indicator = '\$_ '
zsh_indicator = ''
disabled = false
